#!/bin/bash

# Install native dependencies
apt update
apt install -y curl make sudo build-essential protobuf-compiler git

# Fix certificate authorities on armv7
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Install Node
curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt install -y nodejs build-essential

# Install Yarn
npm install -g --unsafe-perm yarn

# Install dependencies
USER=root make depend

# Start development or make release
if [ "$1" = 'dev' ]; then
    make dev
else
    make release
fi
