#!/bin/bash

# Install native dependencies
apt update
apt install -y curl make sudo build-essential protobuf-compiler python3 python3-pip git gnupg2 procps libtool libffi-dev make libzmq3-dev libczmq-dev libgdbm-dev libncurses-dev libssl-dev libreadline-dev libyaml-dev zlib1g-dev bison

# Fix certificate authorities on armv7
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Install and activate the Ruby Version Manager
gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh

# Install Ruby version
rvm install 2.5.1
rvm use 2.5.1

# Install Bundler
gem install bundler --no-ri

# Install ruby-packer
curl -L -o /tmp/rubyc https://github.com/pojntfx/ruby-packer-binaries/releases/download/latest/rubyc.linux-$(uname -m)
install /tmp/rubyc /usr/local/bin

# Install dependencies
USER=root make depend

# Make release
make release
