app:
  multiplier: 1

meta:
  image: pojntfx/mathernet:0.0.2
  dev: false

resources:
  memory: "128Mi"
  cpu: "512m"
  maxReplicas: 10

ingress:
  nodePort: 30005
  domain: mathernet.example.com
  path: /
