// source: proto/mather.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage', null, global);
goog.exportSymbol('proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.displayName = 'proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.displayName = 'proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    firstsummand: jspb.Message.getFieldWithDefault(msg, 1, 0),
    secondsummand: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage;
  return proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFirstsummand(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSecondsummand(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFirstsummand();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getSecondsummand();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional int64 FirstSummand = 1;
 * @return {number}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.prototype.getFirstsummand = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage} returns this
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.prototype.setFirstsummand = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 SecondSummand = 2;
 * @return {number}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.prototype.getSecondsummand = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage} returns this
 */
proto.com.pojtinger.felicitas.grpcExamples.AddInputMessage.prototype.setSecondsummand = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    sum: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage;
  return proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSum();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 Sum = 1;
 * @return {number}
 */
proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.prototype.getSum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage} returns this
 */
proto.com.pojtinger.felicitas.grpcExamples.AddOutputMessage.prototype.setSum = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


goog.object.extend(exports, proto.com.pojtinger.felicitas.grpcExamples);
