// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: mather.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddInputMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstSummand  int64 `protobuf:"varint,1,opt,name=FirstSummand,proto3" json:"FirstSummand,omitempty"`
	SecondSummand int64 `protobuf:"varint,2,opt,name=SecondSummand,proto3" json:"SecondSummand,omitempty"`
}

func (x *AddInputMessage) Reset() {
	*x = AddInputMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddInputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInputMessage) ProtoMessage() {}

func (x *AddInputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInputMessage.ProtoReflect.Descriptor instead.
func (*AddInputMessage) Descriptor() ([]byte, []int) {
	return file_mather_proto_rawDescGZIP(), []int{0}
}

func (x *AddInputMessage) GetFirstSummand() int64 {
	if x != nil {
		return x.FirstSummand
	}
	return 0
}

func (x *AddInputMessage) GetSecondSummand() int64 {
	if x != nil {
		return x.SecondSummand
	}
	return 0
}

type AddOutputMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int64 `protobuf:"varint,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
}

func (x *AddOutputMessage) Reset() {
	*x = AddOutputMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mather_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOutputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOutputMessage) ProtoMessage() {}

func (x *AddOutputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mather_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOutputMessage.ProtoReflect.Descriptor instead.
func (*AddOutputMessage) Descriptor() ([]byte, []int) {
	return file_mather_proto_rawDescGZIP(), []int{1}
}

func (x *AddOutputMessage) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_mather_proto protoreflect.FileDescriptor

var file_mather_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29,
	0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x66, 0x65,
	0x6c, 0x69, 0x78, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2e, 0x67, 0x6f, 0x6d, 0x61, 0x74, 0x68, 0x65, 0x72, 0x22, 0x5b, 0x0a, 0x0f, 0x41, 0x64, 0x64,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x46, 0x69, 0x72, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x46, 0x69, 0x72, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x24, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x24, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x53, 0x75, 0x6d, 0x32, 0x88, 0x01, 0x0a,
	0x06, 0x4d, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x7e, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x3a,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x66,
	0x65, 0x6c, 0x69, 0x78, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x2e, 0x67, 0x6f, 0x6d, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x3b, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x70, 0x6f, 0x6a, 0x74, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x66, 0x65, 0x6c, 0x69, 0x78,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x67, 0x6f,
	0x6d, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6a, 0x6e, 0x74, 0x66, 0x78, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x6d, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mather_proto_rawDescOnce sync.Once
	file_mather_proto_rawDescData = file_mather_proto_rawDesc
)

func file_mather_proto_rawDescGZIP() []byte {
	file_mather_proto_rawDescOnce.Do(func() {
		file_mather_proto_rawDescData = protoimpl.X.CompressGZIP(file_mather_proto_rawDescData)
	})
	return file_mather_proto_rawDescData
}

var file_mather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mather_proto_goTypes = []interface{}{
	(*AddInputMessage)(nil),  // 0: com.pojtinger.felix.grpcExamples.gomather.AddInputMessage
	(*AddOutputMessage)(nil), // 1: com.pojtinger.felix.grpcExamples.gomather.AddOutputMessage
}
var file_mather_proto_depIdxs = []int32{
	0, // 0: com.pojtinger.felix.grpcExamples.gomather.Mather.Add:input_type -> com.pojtinger.felix.grpcExamples.gomather.AddInputMessage
	1, // 1: com.pojtinger.felix.grpcExamples.gomather.Mather.Add:output_type -> com.pojtinger.felix.grpcExamples.gomather.AddOutputMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mather_proto_init() }
func file_mather_proto_init() {
	if File_mather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mather_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddInputMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mather_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOutputMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mather_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mather_proto_goTypes,
		DependencyIndexes: file_mather_proto_depIdxs,
		MessageInfos:      file_mather_proto_msgTypes,
	}.Build()
	File_mather_proto = out.File
	file_mather_proto_rawDesc = nil
	file_mather_proto_goTypes = nil
	file_mather_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MatherClient is the client API for Mather service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MatherClient interface {
	Add(ctx context.Context, in *AddInputMessage, opts ...grpc.CallOption) (*AddOutputMessage, error)
}

type matherClient struct {
	cc grpc.ClientConnInterface
}

func NewMatherClient(cc grpc.ClientConnInterface) MatherClient {
	return &matherClient{cc}
}

func (c *matherClient) Add(ctx context.Context, in *AddInputMessage, opts ...grpc.CallOption) (*AddOutputMessage, error) {
	out := new(AddOutputMessage)
	err := c.cc.Invoke(ctx, "/com.pojtinger.felix.grpcExamples.gomather.Mather/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatherServer is the server API for Mather service.
type MatherServer interface {
	Add(context.Context, *AddInputMessage) (*AddOutputMessage, error)
}

// UnimplementedMatherServer can be embedded to have forward compatible implementations.
type UnimplementedMatherServer struct {
}

func (*UnimplementedMatherServer) Add(context.Context, *AddInputMessage) (*AddOutputMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterMatherServer(s *grpc.Server, srv MatherServer) {
	s.RegisterService(&_Mather_serviceDesc, srv)
}

func _Mather_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInputMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatherServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.pojtinger.felix.grpcExamples.gomather.Mather/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatherServer).Add(ctx, req.(*AddInputMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mather_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.pojtinger.felix.grpcExamples.gomather.Mather",
	HandlerType: (*MatherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Mather_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mather.proto",
}
