# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/mather.proto for package 'com.pojtinger.felicitas.grpcExamples'

require 'grpc'
require 'proto/mather_pb'

module Com
  module Pojtinger
    module Felicitas
      module GrpcExamples
        module Mather
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'com.pojtinger.felicitas.grpcExamples.Mather'

            rpc :Add, ::Com::Pojtinger::Felicitas::GrpcExamples::AddInputMessage, ::Com::Pojtinger::Felicitas::GrpcExamples::AddOutputMessage
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
