name: Docker CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - {
              dir: gomather,
              image: pojntfx/gomather,
              arch: "linux/amd64,linux/arm64/v8",
            }
          - {
              dir: mather-rs,
              image: pojntfx/mather-rs,
              arch: "linux/amd64,linux/arm64/v8",
            }
          - {
              dir: mather.js,
              image: pojntfx/mather-js,
              arch: "linux/amd64,linux/arm64/v8",
            }
          - {
              dir: MatherNet,
              image: pojntfx/mathernet,
              arch: "linux/amd64,linux/arm64/v8",
            }
          - {
              dir: pymather,
              image: pojntfx/pymather,
              arch: "linux/amd64,linux/arm64/v8",
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # - name: Build and push image to Docker Hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ${{ matrix.project.dir }}
      #     file: ${{ matrix.project.dir }}/Dockerfile
      #     platforms: ${{ matrix.project.arch }}
      #     push: true
      #     tags: ${{ matrix.project.image }}:latest

  publish-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    strategy:
      matrix:
        project:
          - { dir: gomather/charts/gomather }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: ${{ matrix.project.dir }}
